spring:
  application:
    name: racehelpr-scraper

scraper:
  kartchrono-url: ${KARTCHRONO_URL}
  topic: raw_chrono_messages
  volume: ${VOLUME_PATH}

kafka:
  topics: raw_chrono_messages
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    com.igorgoose.racehelpr: debug