spring:
  application:
    name: racehelpr-scraper

scraper:
  kartchrono-url: ${KARTCHRONO_URL}
  topic: raw_chrono_messages
  volume: ${VOLUME_PATH}

kafka:
  topics:
    names: raw_chrono_messages
    max-size-bytes: ${MAX_TOPIC_SIZE_BYTES:100000} # 100 MB
    recreate: ${RECREATE_TOPICS:true}
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    com.igorgoose.racehelpr: debug